#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin-vue"
name = "Jellyfin Vue Client"
description.en = "Modern web client for Jellyfin"
description.fr = "Client web moderne pour Jellyfin"

version = "2024.12.21~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/jellyfin/jellyfin-vue"
demo = "https://jf-vue.pages.dev"

fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin-vue"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jellyfin/jellyfin-vue/archive/db5d4a74dec111918818ff347d493e7c6c76dd1c.tar.gz"
    sha256 = "1a457852c5a3397651bef87e4a9f5fa3461386645d288b0deb7e25a44e6c6e80"

    autoupdate.upstream = "https://github.com/jellyfin/jellyfin-vue/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
