#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin-vue"
name = "Jellyfin Vue Client"
description.en = "Modern web client for Jellyfin"
description.fr = "Client web moderne pour Jellyfin"

version = "2024.07.02~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/jellyfin/jellyfin-vue"
demo = "https://jf-vue.pages.dev"

fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin-vue"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jellyfin/jellyfin-vue/archive/5f50e440cc4873bfadd18ff04250496dac428c88.tar.gz"
    sha256 = "0aa6ac7bcff08a2c77d06e66c1956a88a931bc0ad3fefd318631d21bf0a085e1"

    autoupdate.upstream = "https://github.com/jellyfin/jellyfin-vue/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
