#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin-vue"
name = "Jellyfin Vue Client"
description.en = "Modern web client for Jellyfin"
description.fr = "Client web moderne pour Jellyfin"

version = "2024.07.05~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
code = "https://github.com/jellyfin/jellyfin-vue"
demo = "https://jf-vue.pages.dev"

fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin-vue"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jellyfin/jellyfin-vue/archive/7f47ef06cbdc0edc29d66e178932b3791d53f76f.tar.gz"
    sha256 = "f6bdb00ded6d672aa96a2e2429956c46e4c0249b7739211a7c09f63fb4c8124a"

    autoupdate.upstream = "https://github.com/jellyfin/jellyfin-vue/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
